"use strict";
exports.__esModule = true;
var Imdb_1 = require("./Imdb");
var movie_1 = require("../classmovie/movie");
var Professional_1 = require("../classProfessional/Professional");
var fs = require("file-system");
var profesional1 = new Professional_1.Professional("Irati", 29, "female", 80, 1.80, "blond", "green", "asian", false, "vietnamese", 12, "actress");
var profesional2 = new Professional_1.Professional("Dani", 25, "male", 75, 1.60, "brown", "blue", "african", false, "senegalese", 0, "director");
var profesional3 = new Professional_1.Professional("Juan", 89, "male", 70, 1.50, "blond", "brown", "caucasian", true, "irish", 12, "actort");
var profesional4 = new Professional_1.Professional("Pani", 25, "male", 75, 1.60, "brown", "blue", "african", false, "senegalese", 0, "writer");
var actores = [profesional1, profesional3];
var pelicula1 = new movie_1.Movie("Escape Room", 2019, "Estadounidense", "Terror/Suspense");
pelicula1.actors = actores;
pelicula1.director = profesional2;
pelicula1.writer = profesional4;
pelicula1.plataform = "Netflix";
pelicula1.mainCharacterName = "Zoey Davis";
pelicula1.language = "Inlgés";
pelicula1.producer = "Netflix";
pelicula1.distributor = "Netflix";
pelicula1.printMovie();
var pelicula2 = new movie_1.Movie("Harry Potter", 1999, "Estadounidense", "Magia");
pelicula2.actors = actores;
pelicula2.director = profesional2;
pelicula2.writer = profesional4;
pelicula2.plataform = "hbo";
pelicula2.mainCharacterName = "Harry Potter";
pelicula2.language = "Inlgés";
pelicula2.producer = "hbo";
pelicula2.distributor = "hbo";
pelicula2.printMovie();
var pelis = [pelicula1, pelicula2];
var peliculas = new Imdb_1.Imdb(pelis);
console.log(peliculas);
peliculas.Movie[0].printMovie();
var objectToJson = JSON.stringify(peliculas);
fs.writeFileSync("peliculas.json", objectToJson);
