"use strict";
exports.__esModule = true;
var professional_1 = require("../../../professional");
var movie_1 = require("./movie");
var profesional1 = new professional_1.Professional("Irati", 29, "female", 80, 1.80, "blond", "green", "asian", false, "vietnamese", 12, "actress");
var profesional2 = new professional_1.Professional("Dani", 25, "male", 75, 1.60, "brown", "blue", "african", false, "senegalese", 0, "director");
var profesional3 = new professional_1.Professional("Juan", 89, "male", 70, 1.50, "blond", "brown", "caucasian", true, "irish", 12, "actort");
var profesional4 = new professional_1.Professional("Pani", 25, "male", 75, 1.60, "brown", "blue", "african", false, "senegalese", 0, "writer");
var actores = [profesional1, profesional3];
var pelicula = new movie_1.Movie("Escape Room", 2019, "Estadounidense", "Terror/Suspense");
pelicula.actors = actores;
pelicula.director = profesional2;
pelicula.writer = profesional4;
pelicula.plataform = "Netflix";
pelicula.mainCharacterName = "Zoey Davis";
pelicula.language = "Inlgés";
pelicula.producer = "Netflix";
pelicula.distributor = "Netflix";
pelicula.printMovie();
